INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'A trilogia Mass Effect é uma coleção de jogos de ação e RPG aclamada pela crítica. Os jogadores assumem o papel do Comandante Shepard e lideram uma equipe diversificada em uma missão para salvar a galáxia de uma ameaça alienígena mortal. Com uma jogabilidade envolvente, escolhas morais impactantes e um enredo emocionante, a trilogia Mass Effect oferece uma experiência imperdível para os fãs de ficção científica.', 'A Mass Effect Trilogy é uma compilação épica de três jogos que definiram os padrões da narrativa nos videogames. Os jogadores são transportados para um universo sci-fi rico e imersivo, onde assumem o papel do icônico Comandante Shepard. Ao longo da trilogia, eles enfrentam uma raça de máquinas inteligentes chamada Reapers, que ameaça destruir toda a vida conhecida. Com uma jogabilidade envolvente, uma variedade de personagens cativantes e uma história épica que se desenrola através de escolhas significativas, a Mass Effect Trilogy é uma experiência imperdível para os amantes de jogos de ação e RPG.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto, ambientado no Velho Oeste americano. Os jogadores assumem o papel de Arthur Morgan, um fora da lei que faz parte de uma gangue de criminosos. ', 'Red Dead Redemption 2 é um marco na indústria dos videogames, um épico de mundo aberto que transporta os jogadores para o final do século XIX, durante os últimos dias do Velho Oeste americano. Com uma narrativa rica e complexa, o jogo conta a história de Arthur Morgan, um fora da lei em busca de sua própria redenção enquanto enfrenta os desafios e dilemas morais em uma gangue liderada por Dutch van der Linde.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'The Witcher 3: Wild Hunt é um jogo de RPG de ação desenvolvido pela CD Projekt Red, baseado na série de livros de fantasia do autor polonês Andrzej Sapkowski. Os jogadores assumem o papel de Geralt de Rivia, um caçador de monstros conhecido como Witcher, em uma aventura épica por um vasto mundo aberto.', 'The Witcher 3: Wild Hunt é um jogo de RPG de ação aclamado pela crítica e pelos jogadores, que combina uma narrativa profunda e imersiva com uma jogabilidade envolvente. Ambientado em um vasto mundo aberto chamado de Continente, o jogo coloca os jogadores na pele de Geralt de Rivia, um caçador de monstros mutante conhecido como Witcher.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Shadows Die Twice é um jogo eletrônico de ação-aventura desenvolvido pela FromSoftware e publicado pela Activision.', 'É um jogo eletrônico de ação-aventura jogado a partir de uma perspectiva em terceira pessoa. Embora comparado com a série Souls, da FromSoftware, o jogo não apresenta elementos de RPG, como criação de personagens, classes e upgrades de equipamentos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. A história acompanha Jin Sakai, um samurai que precisa proteger a Ilha de Tsushima durante a primeira invasão mongol do Japão.', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura jogado de uma perspectiva em terceira pessoa. Os jogadores tem uma variedade de opções de jogabilidade para alcançar seus objetivos. Podem entrar em confrontos diretos com inimigos usando sua katana, chamado de confronto, que podem resultar em uma série de ataques fatais contra diferentes inimigos.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Super Mario World, originalmente chamado no Japão de Super Mario Bros. 4, é um jogo eletrônico de plataforma desenvolvido pela Nintendo Entertainment Analysis & Development ', '');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Hollow Knight conta a historia de um diminuto guerreiro que decide entrar nas cavernas que abrigam as ruínas do reino de Hallownest. Devido à uma infestação que roubou os insetos de sua inteligência e os reverteu aos seus instintos primitivos, uma grande e próspera nação se tornou apenas resquício do que era. ', 'Ori and the Blind Forest é um Jogo de plataforma em 2D. O jogador controla Ori, um espírito branco guardião de gênero indeterminado, e Sein, que é a luz e os olhos do Espírito da Árvore. Ori pode pular, escalar e usar outras habilidades para se locomover. Sein pode atirar Chamas de Espírito para combater inimigos e quebrar obstáculos. Ori e Sein devem interagir com o ambiente enquanto pulam de plataformas e solucionam quebra-cabeças. Ori enfrenta inimigos enquanto procura restaurar a floresta. O jogador ajuda a personagem a coletar "cacos" de habilidade, de energia, novas habilidades e melhoras. O mundo onde se passa o jogo desenvolve-se ao estilo Metroidvania, com o surgimento de novas habilidade que permitem ao jogador explorar áreas anteriormente inacessíveis.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest é um Metroidvania 2D; um jogo de plataforma com ênfase na exploração, coleta de itens e atualizações e retrocesso para áreas anteriormente inacessíveis . O jogador controla Ori, um espírito guardião branco, e Sein, que é a luz e os olhos da Árvore Espiritual.', '');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead é um clássico jogo de corrida e ação fortemente focado em batalhas contra chefes . Inspirado nos desenhos animados da década de 1930, o visual e o áudio são minuciosamente criados com as mesmas técnicas da época: animação tradicional desenhada à mão, planos de fundo em aquarela e gravações originais de jazz.', 'Além dos gráficos extremamente detalhistas e fiéis aos cartoons da Era de Ouro da animação americana, o jogo chama a atenção pela particularidade, lembrando os jogos de plataforma dos anos 90 em 8 e 16 bit. É possível perceber referências a alguns desses jogos, como Contra, Mega Man X, Gunstar Heroes, Street Fighter III e Thunderforce (quando das fases aéreas). As fases são repletas de inimigos, que atacam das mais diversas formas: saltando em direção ao jogador, caminhando ou atirando projéteis. O jogo também possui fases aéreas, com o personagem pilotando um avião, onde o objetivo é destruir os inimigos atirando projéteis e bombas. Outra referência a jogos vintage está no sistema de navegação entre fases através de um mapa ao estilo Super Mario World e Donkey Kong Country. A grande dificuldade do jogo também é um fator marcante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic CD é um jogo de plataforma side-scrolling semelhante ao Sonic the Hedgehog original . Os jogadores controlam Sonic the Hedgehog enquanto ele se aventura a impedir que seu inimigo, Doutor Robotnik, obtenha as mágicas Time Stones e conquiste um Little Planet.', 'A jogabilidade é praticamente idêntica a dos jogos anteriores, porém com algumas leves mudanças: agora o ato 3 se passa no tempo futuro, que pode ser bom ou ruim. Para que faça-se um bom futuro, Sonic deve voltar ao passado nos atos 1 e 2 por meio das placas com a inscrição "Past", tomando velozes impulsos, ou conseguindo obter todas as Time Stones, joias poderosas do Little Planet e similares as Esmeraldas do Caos (com a exceção de que elas não servem para transformar o ouriço em Super Sonic). Uma vez no passado, ele deverá achar um gerador de robôs e destruí-lo. Caso não consiga, ou consiga só em um dos atos, irá automaticamente para o mau futuro. Sonic também pode ir para o futuro após passar por uma placa "Future" e pegar impulso o suficiente, e seu tipo pode variar dependendo das ações feitas no passado da fase. ');

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);